navikt/amt-tiltaksarrangor-flate

package-lock.json, package.json, public/mockServiceWorker.js, src/App.tsx, src/api/data/bruker.ts, src/api/index.ts, src/api/utils.ts, src/component/page/tiltaksoversikt/FilterMenu.tsx, src/component/page/tiltaksoversikt/TiltaksoversiktPage.tsx, src/component/user-table/UserTable.tsx, src/component/user-table/body/UserTableRow.tsx, src/component/user-table/pagination-bar/PaginationBar.tsx, src/index.tsx, src/mock/data/brukere.ts, src/mock/index.ts, src/store/store-provider.tsx, src/store/tiltaksoversikt-filter-store.ts, src/utils/constants.ts, src/utils/environment.ts, src/utils/text-mappers.ts
Gjør REST-kall mot mocket backend for å søke etter brukere
=> Implementerte enkelt søk i tiltaksoversikten

package-lock.json, package.json, src/App.tsx, src/api/data/bruker.ts, src/api/data/request-types.ts, src/api/index.ts, src/component/page/user-info/UserInfoContent.module.less, src/component/page/user-info/UserInfoContent.tsx, src/component/page/user-info/UserInfoPage.module.less, src/component/page/user-info/UserInfoPage.tsx, src/component/user-table/body/UserTableRow.tsx, src/component/user-table/header/UserTableHeader.tsx, src/index.tsx, src/mock/data/brukere.ts, src/mock/index.ts, src/utils/date-utils.ts, src/utils/index.ts
https://trello.com/c/M2OBHzlf/3-implementere-enkel-detaljvisning-p%C3%A5-person
=> Implementer skisse

src/api/data/deltager.ts, src/component/page/bruker-detaljer/BrukerPaaTiltakDetaljer.tsx, src/component/page/tiltakinstans-detaljer/FilterMeny.tsx, src/component/page/tiltakinstans-detaljer/bruker-oversikt/Rad.tsx, src/component/page/tiltakinstans-detaljer/bruker-oversikt/TabellHeader.tsx, src/component/page/tiltakinstans-detaljer/bruker-oversikt/types.tsx, src/mock/bruker-sok.ts, src/mock/data/brukere.ts, src/mock/dto-mapper.ts
Bruk også fodselsnummer istedenfor fodselsdato i mock data
=> Rename fodselsdato -> fodselsnummer

src/App.tsx, src/api/data/ansatt.ts, src/api/data/deltager.ts, src/api/data/tiltak.ts, src/api/dtoTransformere.ts, src/api/tiltak-api.ts, src/component/felles/menu/virksomhet-velger/VirksomhetVelger.tsx, src/domeneobjekter/ansatt.ts, src/domeneobjekter/deltager.ts, src/domeneobjekter/tiltak.ts, src/mock/data/ansatt.ts, src/mock/dto-mapper.ts, src/mock/handlers/mock-handlers.ts, src/store/valgt-virksomhet-store.ts, src/utils/text-mappers.tsx, src/utils/toEnumValue.ts
Co-authored-by: Magnus Evensberget <magnus.evensberget@nav.no>
=> Oppdaterte API som følge av endringer i backend

src/api/data/tiltak.ts, src/component/page/tiltakinstans-detaljer/TiltakinstansDetaljerPage.tsx, src/component/page/tiltakinstans-detaljer/bruker-oversikt/Rad.module.less, src/component/page/tiltakinstans-detaljer/bruker-oversikt/Rad.tsx, src/component/page/tiltakinstans-detaljer/bruker-oversikt/TabellHeader.module.less, src/component/page/tiltakinstans-detaljer/bruker-oversikt/TabellHeader.tsx, src/domeneobjekter/tiltak.ts, src/mock/data/brukere.ts, src/mock/data/tiltak.ts, src/mock/dto-mapper.ts, src/utils/text-mappers.tsx
- Fikser farge og font weight i tabell over brukere
- Fjerner info fra tiltaksgjennomføring siden som ikke skal være med i mvp(etter å ha pratet med Linn)
=> Fikser småting

src/App.tsx, src/api/data/ansatt.ts, src/api/dtoTransformere.ts, src/api/tiltak-api.ts, src/component/felles/menu/virksomhet-velger/VirksomhetVelger.tsx, src/domeneobjekter/ansatt.ts, src/mock/data/ansatt.ts, src/mock/handlers/mock-handlers.ts
https://trello.com/c/aUWL2bPd/141-normalisere-terminologi-i-koden-arrang%C3%B8r-oppstartdato
=> renamer leverandor til arrangor

src/api/data/deltager.ts, src/api/dtoTransformere.ts, src/component/page/tiltakinstans-detaljer/bruker-oversikt/Rad.tsx, src/component/page/tiltakinstans-detaljer/bruker-oversikt/TabellHeader.tsx, src/component/page/tiltakinstans-detaljer/bruker-oversikt/types.tsx, src/domeneobjekter/deltager.ts, src/mock/data/brukere.ts, src/mock/dto-mapper.ts
https://trello.com/c/2IL3BkKN/92-vise-kolonne-dato-s%C3%B8kt-inn
=> Viser kolonne med dato deltaker ble registrert

src/api/data/deltaker.ts, src/api/dtoTransformere.ts, src/component/page/bruker-detaljer/BrukerPaaTiltakDetaljer.tsx, src/component/page/gjennomforing-detaljer/GjennomforingDetaljerPage.tsx, src/component/page/gjennomforing-detaljer/deltaker-oversikt/Rad.tsx, src/domeneobjekter/deltaker.ts, src/mock/data/brukere.ts, src/utils/deltaker-status-utils.test.ts, src/utils/deltaker-status-utils.ts, src/utils/filtrering-utils.ts
- Brukere som har slutta og er eldre enn 2 uker skal ikke vises
https://trello.com/c/GCTJtH1l/44-statuser-fjerne-brukere-fra-deltaker-oversikten-etter-x-tid
https://github.com/navikt/amt-tiltak/pull/109
=> Filtrere ut gamle brukere som har slutta

src/component/page/gjennomforing-detaljer/deltaker-oversikt/Rad.tsx, src/component/page/gjennomforing-detaljer/deltaker-oversikt/StatusMerkelapp.module.scss, src/component/page/gjennomforing-detaljer/deltaker-oversikt/StatusMerkelapp.tsx
https://trello.com/c/YDYflaPP/230-vise-statusmerkelapp-i-deltakerlista
=> Merkelapp status

src/utils/deltaker-status-utils.ts
=> Midlertidig sette ned tiden det tar før brukere går ut av lista

src/component/page/bruker-detaljer/BrukerPaaTiltakDetaljer.tsx
https://trello.com/c/bIFbF06G/163-personsiden-vise-dato-for-n%C3%A5r-personen-fjernes
=> Vise dato brukeren går ut av lista på de som er ikke aktuelle

src/component/PageViewMetricCollector.tsx, src/component/page/bruker-detaljer/kopier-knapp/KopierKnapp.tsx, src/component/page/gjennomforing-detaljer/FilterMeny.tsx, src/component/page/gjennomforing-detaljer/deltaker-oversikt/Rad.tsx, src/component/page/gjennomforing-detaljer/deltaker-oversikt/SorterbarKolonneHeader.tsx, src/utils/amplitude-utils.ts
https://trello.com/c/CgXN2aE9/241-m%C3%A5linger-antall-klikk-her-og-der
=> Logger klikk på diverse

cypress.json, src/utils/bruker-utils.ts
https://trello.com/c/Ou6Rqdf5/298-mellomnavn-vises-som-undefined
=> Fikser at brukers mellomnavn bare vises om det finnes

src/component/sesjon-notifikasjon/SesjonNotifikasjon.tsx
Co-authored-by: Alexander Gård <alexander.gard@nav.no>
=> Fikser fokus og timeout på sesjonsalerter

src/component/sesjon-notifikasjon/SesjonNotifikasjon.module.scss, src/component/sesjon-notifikasjon/SesjonNotifikasjon.tsx
Co-authored-by: Alexander Gård <alexander.gard@nav.no>
=> Gjør sesjon notifikasjon sticky

src/component/page/bruker-detaljer/nav-info-panel/NavInfoPanel.tsx, src/component/page/bruker-detaljer/nav-info-panel/NavInfoVeileder.tsx, src/mock/data/brukere.ts
Lagt Veileder inn i egen fil, om Deltaker ikke har veileder vil det komme en melding "Det er ikke registrert en NAV-veileder til denne deltakeren."
=> 456: De som ikke har Veileder

src/component/page/gjennomforing-page/gjennomforing-liste/GjennomforingListe.tsx, src/component/page/legg-til-deltakerliste/gjennomforing-liste/GjennomforingListe.tsx, src/mock/data/tiltak.ts, src/utils/sortering-utils.ts
Co-authored-by: Alexander Gård <alex.gaard@hotmail.com>
=> Sorter visning av forskjellige tiltak

src/App.tsx, src/Routes.tsx, src/component/felles/ikon-lenke/IkonLenke.module.scss, src/component/felles/ikon-lenke/IkonLenke.tsx, src/component/felles/menu/Banner.tsx, src/component/page/gjennomforing-page/GjennomforingListePage.tsx, src/component/page/informasjon-page/InformasjonPage.tsx, src/component/page/landing-page/LandingPage.module.scss, src/component/page/landing-page/LandingPage.tsx, src/component/page/personopplysninger-page/PersonopplysningerPage.module.scss, src/component/page/personopplysninger-page/PersonopplysningerPage.tsx, src/index.tsx, src/navigation.ts, src/store/data-store.ts, src/store/store-provider.tsx
Lagt til routes for ikke- og inloggede brukere.
Co-authored-by: Alexander Gård <alex.gaard@hotmail.com>
=> Legg til personopplysninger-page

package-lock.json, package.json
Samlet snyk oppgraderinger for å spare tid
=> Oppgraderer dependencier

src/api/data/deltaker.ts, src/api/data/endringsmelding.ts, src/api/data/tiltak.ts, src/api/tiltak-api.ts, src/component/page/bruker-detaljer/BrukerPaaTiltakDetaljer.tsx, src/component/page/bruker-detaljer/deltakelses-periode/Deltakelsesperiode.tsx, src/component/page/bruker-detaljer/deltakelses-periode/SluttdatoPanel.tsx, src/component/page/bruker-detaljer/deltakelses-periode/StardatoPanel.tsx, src/component/page/gjennomforing-detaljer/deltaker-oversikt/Rad.tsx, src/component/page/gjennomforing-detaljer/deltaker-oversikt/TabellBody.tsx, src/component/page/gjennomforing-detaljer/deltaker-oversikt/sortering.ts, src/mock/data/auth.ts, src/mock/data/brukere.ts, src/mock/data/endringsmelding.ts, src/mock/data/id.ts, src/mock/handlers/dev-proxy-handlers.ts, src/mock/handlers/local-app-handlers.ts, src/mock/handlers/mock-handlers.ts
Co-authored-by: Alexander Gård <alex.gaard@hotmail.com>
=> Synce opp api med endringer i amt-tiltak backend

src/component/page/gjennomforing-detaljer/deltaker-oversikt/sortering.ts
Co-authored-by: Alexander Gård <alexander.gard@nav.no>
=> Fikser sortering på start og sluttdato

src/component/page/gjennomforing-page/GjennomforingListePage.tsx
=> Fjern filtrering av gjennomforinger pa status

src/component/page/bruker-detaljer/DeltakerDetaljer.module.scss, src/component/page/bruker-detaljer/DeltakerDetaljer.tsx, src/component/page/gjennomforing-detaljer/FilterMeny.module.scss, src/component/page/gjennomforing-detaljer/GjennomforingDetaljerPage.module.scss, src/component/page/gjennomforing-detaljer/GjennomforingDetaljerPage.tsx, src/component/page/gjennomforing-detaljer/deltaker-oversikt/DeltakerOversiktTabell.module.scss, src/component/page/gjennomforing-detaljer/deltaker-oversikt/DeltakerOversiktTabell.tsx
https://trello.com/c/OKf9VriK/621-responsiv-mobil-og-zoom-200-deltakeroversikten
=> WCAG 1.4.10 Tilpasse side for mobil- og 200%-zoom

src/api/data/deltaker.ts, src/api/tiltak-api.ts, src/component/page/bruker-detaljer/DeltakerDetaljer.tsx, src/component/page/bruker-detaljer/DeltakerDetaljerPage.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/DeltakelseInfo.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/EndreDeltakelseKnapp.tsx, src/mock/data/brukere.ts, src/mock/handlers/mock-handlers.ts
https://github.com/navikt/amt-tiltak/pull/331
=> Fjerner begrensning på endringsmeldinger for skjermede personer

src/api/auth-api.ts, src/api/feature-toggle-api.ts, src/api/tiltak-api.ts, src/api/utils.ts
Co-authored-by: Tormod Fossum <tormod.fossum@nav.no>
Co-authored-by: Alexander Gård <alexander.gard@nav.no>
=> Legger url og ekstra info på logger

src/component/sesjon-notifikasjon/SesjonNotifikasjon.tsx
for å rette problem med at man går glipp av tidsrommet hvor man skulle fått alert eller blitt logget ut
=> Bruker setInterval isteden for setTimeout

src/component/page/bruker-detaljer/deltaker-detaljer/EndreDeltakelseKnapp.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/AvsluttDeltakelseModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/EndreOppstartModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/EndreProsentDeltakelseModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/ForlengDeltakelseModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/LeggTilEndreOppstartModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/LeggTilOppstartModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/SettIkkeAktuellModal.tsx
https://trello.com/c/Y6e35Hzc/810-fjerne-boksen-godkjent-av-nav-veileder-p%C3%A5-alle-endringer-som-gj%C3%B8res-p%C3%A5-deltakere-av-vta
=> Skjuler panel for å godkjenne vilkår for vta tiltaket

src/component/page/deltakerliste-veileder/FilterMenyDeltakerliste.tsx, src/component/page/deltakerliste-veileder/FilterMenyVeiledertype.tsx, src/component/page/gjennomforing-detaljer/FilterMenyStatus.tsx, src/mock/handlers/mock-handlers.ts, src/mock/index.ts
https://trello.com/c/Ppa58vjZ/835-fiks-feil-bruk-av-checkbokser-som-gir-warning
=> #835: Fikser feil i håndtering av checkbokser som gir console warning

src/component/page/ingen-rolle-page/IngenRollePage.module.scss
https://trello.com/c/yYFYfqMp/814-gr%C3%A5-stripe-over-dekorat%C3%B8ren
=> #814: Retter feil som fører til grå stripe over dekoratøren

src/api/data/deltaker.ts, src/component/page/deltakerliste-veileder/RadVeileder.tsx, src/mock/data/tiltak.ts
https://trello.com/c/rLLbNAIq/830-m%C3%A5-fikses-veileder-ser-ikke-endringsmeldinger-i-tabellen
=> skal vise endringsmeldinger (start/slutt) i veiledertabell

src/component/page/gjennomforing-detaljer/GjennomforingDetaljerPage.tsx
https://trello.com/c/nQRGrwUv/787-vise-gjennomf%C3%B8ringinfo-over-filteringsmenyer
=> #787: Viser info om gjennomføring over filtreringsmenyer

src/component/page/bruker-detaljer/tildel-veileder-modal/TildelVeilederModal.tsx
https://trello.com/c/1xRboz93/829-hvis-noe-feiler-ved-tildeling-av-veileder-s%C3%A5-f%C3%A5r-man-ingen-tilbakemelding-i-brukergrensesnittet
=> #829: Viser feilmelding om tildeling feiler i backend

package.json, pnpm-lock.yaml, src/component/page/bruker-detaljer/deltaker-detaljer/EndringTypeIkon.module.scss, src/component/page/bruker-detaljer/deltaker-detaljer/EndringTypeIkon.tsx
https://trello.com/c/z7hcjLsm/921-oppdatere-ikoner-etter-designsystemet
=> Oppdaterer ikoner til siste versjon

src/api/data/deltaker.ts, src/mock/data/brukere.ts
https://trello.com/c/wQLl1Eez/919-kurs-ikke-aktuell-filteret-skjules
=> fjerner IKKE_AKTUELL for kursdeltakere

src/component/page/deltakerliste-detaljer/deltaker-oversikt/DeltakerOversiktTabell.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyMedveileder.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyStatus.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyVeiledere.tsx, src/component/page/deltakerliste-detaljer/store/koordinator-table-filter-store.ts, src/component/page/veileder/MineDeltakereTabell.tsx, src/component/page/veileder/filter-meny/FilterMenyDeltakerliste.tsx, src/component/page/veileder/filter-meny/FilterMenyStatus.tsx, src/component/page/veileder/filter-meny/FilterMenyVeilederType.tsx, src/component/page/veileder/store/veileder-table-filter-store.ts, src/store/tiltaksoversikt-sok-store.ts
* Reduserer kodeduplisering ved å flytte store-relatert kode til store
* Fikser rare greier hvor man bruker forskjellige stores til det samme
=> Reduserer kodeduplisering ved å flytte store-relatert kode til store

src/component/page/deltakerliste-detaljer/DeltakerlisteDetaljerPage.tsx, src/component/page/deltakerliste-detaljer/deltaker-oversikt/DeltakerOversiktTabell.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyMedveileder.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyStatus.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyVeiledere.tsx, src/component/page/deltakerliste-detaljer/store/koordinator-filter-meny-store-provider.ts, src/component/page/veileder/MineDeltakerePage.tsx, src/component/page/veileder/MineDeltakereTabell.tsx, src/component/page/veileder/filter-meny/FilterMenyDeltakerliste.tsx, src/component/page/veileder/filter-meny/FilterMenyStatus.tsx, src/component/page/veileder/filter-meny/FilterMenyVeilederType.tsx, src/component/page/veileder/store/veileder-filter-meny-store-provider.ts, src/store/store-provider.tsx
* Renamer store providere til å følge vanlig navnekonvensjon
* Fikser feil med at filtervalg blir glemt når man trykker seg inn på deltaker
https://trello.com/c/WJ8DiNSA/887-bugfix-huske-filter
=> Fikser feil som gjør at valg man gjør i filtermeny blir borte når man trykker seg inn på deltaker

src/component/page/bruker-detaljer/deltaker-detaljer/DeltakelseInfo.tsx
* https://trello.com/c/ZFsgtXZS/933-bug-mangler-fjern-deltaker-alertstripe-p%C3%A5-fullf%C3%B8rt
=> Deltakere med status fullført skal også kunne fjerne deltaker

src/component/page/deltakerliste-detaljer/deltaker-oversikt/deltaker-tabell/Rad.tsx, src/component/page/veileder/RadVeileder.tsx, src/component/page/veileder/TabellBodyVeileder.tsx
https://trello.com/c/iMD8rP6y/931-endre-sluttdato-foresl%C3%A5tt-dato-og-m%C3%A5-vises-i-tabellen
=> Viser endringsmelding sluttdato i tabell med deltakere for veileder og koordinator

src/component/page/veileder/filter-meny/FilterMenyVeilederType.tsx
https://trello.com/c/w5qNCIgG/928-rekkef%C3%B8lge-p%C3%A5-veileder-medveileder-filteret
=> setter rekkefølge for veileder-filter

src/component/page/bruker-detaljer/deltaker-detaljer/EndreDeltakelseKnapp.tsx
Endres etter tilbakemeldinger fra brukere
=> deltakere på ikke-kurs, skal vise forleng isteden for endre sluttdato

src/component/page/bruker-detaljer/tildel-veileder-modal/TildelVeilederModal.tsx
https://trello.com/c/yJLvcLOJ/909-tekstendring-i-modal-endre-veileder
=> ender veileder-infotekst

src/Routes.tsx, src/component/page/bruker-detaljer/DeltakerDetaljer.tsx, src/component/page/deltakerliste-detaljer/deltaker-oversikt/deltaker-tabell/Rad.tsx, src/component/page/deltakerliste-detaljer/deltaker-oversikt/deltaker-tabell/TabellHeader.tsx, src/component/page/mine-deltakerlister-page/MineDeltakerlisterPage.tsx, src/utils/toggle.ts, src/utils/veileder-utils.ts
https://trello.com/c/ecCO0aHb/878-formatere-navnet-p%C3%A5-veileder-og-medveileder
https://trello.com/c/5oTam42C/969-fjerne-veileder-toggle-fra-amt-tiltaksarrangor-flate
=> Formattering navn

src/component/page/deltakerliste-detaljer/DeltakerlisteDetaljerPage.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyChips.tsx, src/component/page/veileder/MineDeltakerePage.tsx, src/component/page/veileder/filter-meny/FilterMenyChips.tsx, src/component/page/veileder/filter-meny/FilterMenyVeilederType.tsx, src/globals.module.scss, src/utils/text-mappers.tsx
Legge til fjerne filter med chips:
https://trello.com/c/Kr9B3EJu/832-vise-hva-man-har-filtrert-p%C3%A5-chipss
=> Legge til chips for å fjerne filtrering

.github/workflows/cypress-cache.yaml, .github/workflows/cypress.yaml, .github/workflows/deploy.yaml, .github/workflows/gh-pages.yaml, .github/workflows/lint-and-test.yaml, .github/workflows/pr-deploy.yaml, README.md, pnpm-lock.yaml
Trello: https://trello.com/c/8LUAUqsH/984-oppdatere-designsystemet-til-v-400
=> Oppgrader pnpm versjon

package.json, pnpm-lock.yaml, public/mockServiceWorker.js, src/component/page/bruker-detaljer/deltaker-detaljer/DropDownButton.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/EndreDeltakelseKnapp.module.scss, src/component/page/bruker-detaljer/deltaker-detaljer/EndreDeltakelseKnapp.tsx
https://trello.com/c/8LUAUqsH/984-oppdatere-designsystemet-til-v-400
=> Bump aksel designsystem

.eslintrc.json, src/component/felles/status-merkelapp/StatusMerkelapp.tsx, src/component/page/deltakerliste-detaljer/DeltakerlisteDetaljerPage.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyDeltakerListeDetaljer.tsx, src/component/page/deltakerliste-detaljer/store/koordinator-filter-meny-store-provider.ts
https://trello.com/c/WEqvX5yy/1023-fiks-filter-valg-hvis-deltakerliste-ikke-inneholder-filteret
=> Fiks gyldige filter

.eslintrc.json, cypress/e2e/accessibility_spec.js, package.json, pnpm-lock.yaml, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/AarsakRadioMedBeskrivelse.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/AvsluttDeltakelseModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/SendTilNavKnapp.module.scss, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/SendTilNavKnapp.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/SettIkkeAktuellModal.tsx
https://trello.com/c/ZYaRQgiF/974-skjemavalidering-fritekstfelt-annet
=> Skjemavalidering fritekst annet

.eslintrc.json, src/component/felles/base-modal/BaseModal.tsx, src/component/page/administrer-deltakerlister-page/AdministrerDeltakerlisterPage.tsx, src/component/page/administrer-deltakerlister-page/underenheter-pa-overenhet/deltakerlister-pa-virksomhet/deltakerlister/DeltakerlistePanel.tsx, src/component/page/bruker-detaljer/DeltakerDetaljerHeader.tsx, src/component/page/bruker-detaljer/bestilling/Bestilling.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/EndreDeltakelseKnapp.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/AarsakRadioMedBeskrivelse.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/AvsluttDeltakelseModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/SendTilNavKnapp.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/SettErAktuellModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/SettIkkeAktuellModal.tsx, src/component/page/bruker-detaljer/tildel-veileder-modal/TildelVeilederModal.tsx, src/component/page/bruker-detaljer/veileder-panel/VeilederPanel.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyDeltakerListeDetaljer.tsx
https://trello.com/c/SLRM8U0z/948-uu-lukking-av-endringsmelding-modal-fungerer-ikke-som-forventet-i-jaws
=> Fiks baseModal skjul innhold bak og sett fokus tilbake ved lukking

src/component/page/administrer-deltakerlister-page/AdministrerDeltakerlisterPage.tsx
https://trello.com/c/zhl9hGLr/1060-tekstendring-inne-p%C3%A5-legg-til-deltakerliste
=> Endre tekst for legge til deltakerliste hvis det er ingen deltakerlister

src/component/page/deltakerliste-detaljer/deltaker-oversikt/DeltakerOversiktTabell.tsx, src/component/page/veileder/MineDeltakereTabell.tsx
https://trello.com/c/PllrVWOS/1003-filtrering-legge-til-aria-live-med-info-om-oppdatering-fra-filtreringen-dette-gjelder-b%C3%A5de-filtrering-og-fjerne-chips
=> legge til aria-live for filtreing

package.json, pnpm-lock.yaml, src/component/felles/base-modal/BaseModal.module.scss, src/component/felles/base-modal/BaseModal.tsx
https://trello.com/c/NMoTu8HC/1078-oppdater-til-versjon-5-av-designsystemet
=> Bump designsystem til v5

.github/dependabot.yml
https://trello.com/c/98AWvxFu/1086-sette-opp-dependabot-for-frontendflater
=> Legge til dependabot.yaml

.gitignore, src/api/data/deltaker.ts, src/component/page/bruker-detaljer/DeltakerAdresse.tsx, src/component/page/bruker-detaljer/DeltakerDetaljerHeader.module.scss, src/component/page/bruker-detaljer/DeltakerDetaljerHeader.tsx, src/component/page/bruker-detaljer/DeltakerDetaljerPage.tsx, src/component/page/bruker-detaljer/nav-info-panel/NavInfoPanel.tsx, src/mock/data/brukere.ts, src/mock/handlers/mock-handlers.ts, src/utils/deltaker-utils.ts, src/utils/text-mappers.tsx
https://trello.com/c/gGxZ2X3a/753-vise-deltakers-adresse-i-deltakeroversikten
=> Legge til adresse for deltakere

.vscode/settings.json, src/component/page/deltakerliste-detaljer/deltaker-oversikt/DeltakerOversiktTabell.module.scss, src/component/page/deltakerliste-detaljer/deltaker-oversikt/deltaker-tabell/TabellHeader.module.scss, src/component/page/deltakerliste-detaljer/deltaker-oversikt/deltaker-tabell/TabellHeader.tsx, src/component/page/veileder/MineDeltakereTabell.module.scss, src/component/page/veileder/MineDeltakereTabell.tsx, src/component/page/veileder/TabellHeader.module.scss, src/component/page/veileder/TabellHeaderVeileder.tsx, src/index.scss
https://trello.com/c/AoIYdeDp/1051-sticky-header-p%C3%A5-tabellene
=> Ha sticky header på tabellene

src/api/data/endringsmelding.ts, src/api/tiltak-api.ts, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/EndreOppstartModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/EndreSluttdatoModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/LeggTilEndreDatoModal.tsx, src/component/page/deltakerliste-detaljer/deltaker-oversikt/deltaker-tabell/Rad.tsx
Det blir en form for å angre datoen som er satt.
=> Tillat null-dato i endre oppstartsdato melding

src/api/data/deltaker.ts, src/component/page/deltakerliste-detaljer/deltaker-oversikt/deltaker-tabell/Rad.module.scss, src/component/page/deltakerliste-detaljer/deltaker-oversikt/deltaker-tabell/Rad.tsx, src/mock/handlers/mock-handlers.ts
https://trello.com/b/bQ4yVFJd/team-komet
=> legge til vurdering på deltakerlista

src/mock/data/brukere.ts, src/mock/data/index.ts, src/mock/data/tiltak.ts
https://trello.com/c/mEm0Up7n/1128-mulig-fix-i-demo
=> Fiks mock data

cypress/e2e/accessibility_spec.js, src/component/page/mine-deltakerlister-page/mine-deltakere/MineDeltakerePanel.module.scss, src/component/page/mine-deltakerlister-page/mine-deltakere/MineDeltakerePanel.tsx, src/mock/data/brukere.ts
https://trello.com/c/ll3V6X15/1123-mine-deltakere-er-buggy-i-demoappen-noe-vi-kan-fikse
=> bytt til router lenke

src/component/page/bruker-detaljer/deltaker-detaljer/DropDownButton.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/EndreDeltakelseKnapp.module.scss, src/component/page/bruker-detaljer/deltaker-detaljer/EndreDeltakelseKnapp.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/vurdering/VurderDeltakelseKnapp.module.scss, src/component/page/bruker-detaljer/deltaker-detaljer/vurdering/VurderDeltakelseKnapp.tsx
https://trello.com/c/rqW98NYx/1095-endre-deltakelse-knapp-forenkle
=> fiks dropdown for skjermleser og fjerne unødvendig tittel

src/component/page/bruker-detaljer/deltaker-detaljer/EndreDeltakelseKnapp.tsx
https://trello.com/c/a7Z0l5yU/1159-endre-sluttdato-skal-ogs%C3%A5-bli-tilgjengelig-for-tiltak-med-l%C3%B8pende-inntak
=> Legge til endre sluttdato for status har_sluttet

src/component/page/bruker-detaljer/deltaker-detaljer/endringsmelding/Endringsmeldinger.module.scss, src/component/page/bruker-detaljer/deltaker-detaljer/endringsmelding/HistoriskeEndringsmeldinger.module.scss, src/component/page/bruker-detaljer/deltaker-detaljer/endringsmelding/HistoriskeEndringsmeldinger.tsx
https://trello.com/c/R9CUdeSm/1172-sm%C3%A5fiks-historikk
=> Fiks historiske denringsmeldinger

src/api/data/tiltak.ts
https://trello.com/c/5971OHtX/1204-legge-til-ny-endre-status-p%C3%A5-gjennomf%C3%B8ringer
BFF sender ikke lenger denne verdien.
=> fjerner APENT_FOR_INNSOK

src/component/page/bruker-detaljer/deltaker-detaljer/EndreDeltakelseKnapp.tsx
https://trello.com/c/o8DGWttT/1209-sende-oppstartsdato-p%C3%A5-deltakere-med-status-vurderes
=> skal kunne endre/legge til oppstartsdato for status vurderes

src/api/data/deltaker.ts, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyStatus.tsx
https://trello.com/c/J7eQJvtj/1226-endre-mapping-fra-arenastatus-til-v%C3%A5re-statuser
=> VURDERES brukes også for løpende inntak

src/component/page/ingen-rolle-page/IngenRollePage.tsx
https://trello.com/c/U39FHjAa/1229-bytte-lenke-p%C3%A5-innlogget-side-du-har-ikke-tilgang
=> fikser altinn-lenke

src/component/page/administrer-deltakerlister-page/AdministrerDeltakerlisterPage.module.scss, src/component/page/administrer-deltakerlister-page/AdministrerDeltakerlisterPage.tsx
https://trello.com/c/t0r2vT3j/1626-legge-til-info-om-endring-p%C3%A5-deltakeroversikten
=> infomelding om når deltakerlister blir tilgjengelige

src/mock/data/brukere.ts
https://trello.com/c/gY2Hgj6J/1663-fjerne-brukere-med-adresseskjerming-fra-demo-appen
=> Fjerne adressebeskyttede fra mock data

src/component/page/bruker-detaljer/deltaker-detaljer/EndreDeltakelseKnapp.module.scss, src/component/page/bruker-detaljer/deltaker-detaljer/EndreDeltakelseKnapp.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/AarsakSelector.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/EndreProsentDeltakelseModal.module.scss, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/EndreProsentDeltakelseModal.tsx
https://trello.com/c/8JXJUCIV/1684-sm%C3%A5fiks-deltakeroversikten-forslag-til-endringer
=> Smafiks for endringsknapp og modaler

src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/EndreOppstartModal.module.scss, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/EndreOppstartModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/LeggTilOppstartModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/SendTilNavKnapp.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/endringsmodal/Endringsmodal.tsx
https://trello.com/c/z6wyRby1/1703-endre-deltaker-legg-til-oppstartsdato
=> Leggtiloppstartsdato fix

src/component/page/administrer-deltakerlister-page/AdministrerDeltakerlisterPage.tsx
https://trello.com/c/LizeHV3m/1627-fjerne-info-om-endring-p%C3%A5-deltakeroversikten
=> fjerner infomelding om endring

src/component/felles/alert-info-message/AlertInfoMessage.module.scss, src/component/felles/alert-info-message/AlertInfoMessage.tsx, src/component/page/deltakerliste-detaljer/deltaker-oversikt/DeltakerOversiktTabell.tsx, src/component/page/veileder/MineDeltakereTabell.tsx
https://trello.com/c/VXIRYWUE/1760-innf%C3%B8ring-til-arrang%C3%B8r-i-deltakeroversikten-lanseringsdato
=> Legg til alert stripe melding om lansering

src/component/felles/status-merkelapp/StatusMerkelapp.module.scss, src/component/felles/status-merkelapp/StatusMerkelapp.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/forslag/Forslag.module.scss, src/component/page/bruker-detaljer/deltaker-detaljer/forslag/ForslagEndringsdetaljer.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/forslag/forslagUtils.ts, src/globals.module.scss
https://trello.com/c/IsY1LHjU/1177-sm%C3%A5fiks-farge-p%C3%A5-statusetikettene
=> fiks statustag farger, og smafiks for forslag

src/api/tiltak-api.ts, src/api/utils.ts
https://trello.com/c/Tlfkl4AU/1773-ignorere-401-feil-i-sentry-logger-amt-tiltaksarrangor-flate
=> Ikke logg 401 feil til sentry

src/component/page/bruker-detaljer/deltaker-detaljer/DeltakelseInfo.tsx
https://trello.com/c/PwdDpaeX/1726-skru-av-gammel-endringsmelding-funksjonalitet
=> Fjerne endringsmeldingsknappen for AFT så lenge vi ikke er master

src/component/page/bruker-detaljer/deltaker-detaljer/EndreDeltakelseKnapp.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/EndreProsentDeltakelseModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/validering/deltakelsesmengdeValidering.ts
https://trello.com/c/hIha8DEx/1882-bug-kan-ikke-sende-forslag-om-endring-p%C3%A5-kun-antall-dager-per-uke
=> Fjern validering på deltakelses prosent lik som før

src/api/data/historikk.ts, src/component/page/bruker-detaljer/deltaker-detaljer/historikk/HistorikkEndring.tsx, src/mock/data/historikk.ts
https://trello.com/c/dAIOux0V/1782-se-endringer-tiltaksarrang%C3%B8r-skal-se-den-%C3%B8verste-delen-av-innholds-teksten
=> Vis ledeteksten for innhold som er endret

LICENSE.md, README.md, src/component/felles/alert-info-message/AlertInfoMessage.tsx, src/component/page/administrer-deltakerlister-page/AdministrerDeltakerlisterPage.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/LeggTilOppstartModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/SendTilNavKnapp.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/VeilederConfirmationPanel.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/endringsmodal/Endringsmodal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endringsmelding/Endringsmeldinger.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/fjern-deltaker-modal/FjernDeltakerModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/forslag/AktiveForslag.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/forslag/ForslagStatusTag.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/historikk/HistorikkEndring.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/vurdering/SettOppfyllerIkkeKravenelModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/vurdering/SettOppfyllerKravenelModal.tsx, src/component/page/bruker-detaljer/nav-info-panel/NavInfoPanel.tsx, src/component/page/bruker-detaljer/nav-info-panel/NavInfoVeileder.tsx, src/component/page/bruker-detaljer/tildel-veileder-modal/TildelVeilederModal.tsx, src/component/page/deltakerliste-detaljer/TiltakInfo.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyNavKontor.tsx, src/component/page/ingen-rolle-page/IngenRollePage.tsx, src/index.scss, src/mock/data/brukere.ts, src/mock/data/historikk.ts, src/utils/text-mappers.tsx
https://trello.com/c/AtyhSi8F/1813-endre-p%C3%A5-innf%C3%B8ringen-i-deltakeroversikten
og
https://trello.com/c/AcqzDuQy/1906-tydeliggj%C3%B8re-for-arrang%C3%B8r-og-veileder-at-det-de-skriver-vil-v%C3%A6re-synlig-for-brukeren
=> Oppdatert lanseringsinfo og endre info for forslag

src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/varighet.ts
https://trello.com/c/SXIKCy1c/1908-endre-varighet-avklaring-arr-digitalt-oppf%C3%B8lgingstiltak
=> endrer maksvarighet for tiltakstyper

src/api/data/deltaker.ts, src/component/page/veileder/RadVeileder.module.scss, src/component/page/veileder/RadVeileder.tsx, src/component/page/veileder/TabellHeaderVeileder.tsx, src/component/page/veileder/sortering.ts, src/mock/data/tiltak.ts, src/utils/deltaker-utils.ts
https://trello.com/c/VvdhkFOQ/712-fange-opp-i-listen-til-ta-at-nytt-forslag-er-sendt-og-endringer-er-gjort
=> Vise aktiv endring i arrangør veilderes liste

src/component/felles/alert-info-message/AlertInfoMessage.tsx
https://trello.com/c/diX51wKh/1943-oppdatere-infomelding
=> Endre info melding til TA

src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/LeggTilOppstartModal.tsx
https://trello.com/c/5xYCeqg9/1937-vta-fjerne-varighet-sluttdato-i-modal-legg-til-oppstartsdato
=> Ikke velg sluttdato i legg til oppstartsdato for VTA

src/component/page/bruker-detaljer/deltaker-detaljer/DeltakelseInfo.tsx
OBS! Denne skal mergest Torsdag 14. november etter kl 15:00
https://trello.com/c/AWLBbltM/1932-skru-av-endringsmeldinger-for-arr-oppf%C3%B8lging-og-avklaring
=> Skru av endringer for Avklaring, Oppfølging og ARR så lenge vi ikke er master

src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/EndreOppstartModal.tsx, src/mock/data/brukere.ts, src/mock/data/id.ts, src/mock/data/index.ts
https://trello.com/c/G94Wmoer/1957-endre-startdato-vta-ta-bort-varighet-sluttdato-dersom-deltaker-ikke-har-en-sluttdato
=> Varighet og sluttdato skal ikke velges for VTA når vi er master. Fiks

src/component/felles/alert-info-message/AlertInfoMessage.tsx
=> Endrer alertstripe som vises etter lansering

src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/ForlengDeltakelseModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/SluttdatoVelger.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/use-sluttdato.ts
https://trello.com/c/GitHHKM1/1959-endring-i-varighet-sluttdato-p%C3%A5-hurtigvalgene
=> skal bruke eksklusiv varighet

src/hooks/useFeatureToggle.ts
https://trello.com/c/v4xePS94/1929-etter-lansering-legge-til-de-to-neste-tiltakstypene-i-listen-over-tiltak-vi-kanskje-er-master-for
=> legger til nye tiltakstyper

src/api/data/historikk.ts
https://trello.com/c/W2Hrjp65/2010-bug-feilmelding-p%C3%A5-se-endringer-hos-arrang%C3%B8r
=> sluttdato er optional for legg til oppstartsdato

src/component/page/bruker-detaljer/deltaker-detaljer/DeltakelseInfo.tsx
https://trello.com/c/wyQZ7Tx3/2003-skru-av-endringsmeldinger-for-vta-og-digiopparb
=> Skru av endringsmeldinger for VTA og DIGIOPPARB

src/api/data/deltaker.ts, src/component/page/deltakerliste-detaljer/deltaker-oversikt/DeltakerOversiktTabell.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyChips.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyDeltakerListeDetaljer.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyHendelser.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyMedveileder.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyNavKontor.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyStatus.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyVeiledere.tsx, src/component/page/deltakerliste-detaljer/store/koordinator-filter-meny-store-provider.ts, src/component/page/veileder/MineDeltakerePage.tsx, src/component/page/veileder/MineDeltakereTabell.tsx, src/component/page/veileder/filter-meny/FilterMenyChips.tsx, src/component/page/veileder/filter-meny/FilterMenyDeltakerliste.tsx, src/component/page/veileder/filter-meny/FilterMenyHendelser.tsx, src/component/page/veileder/filter-meny/FilterMenyStatus.tsx, src/component/page/veileder/filter-meny/FilterMenyVeilederType.tsx, src/component/page/veileder/store/veileder-filter-meny-store-provider.ts, src/mock/data/brukere.ts, src/mock/handlers/mock-handlers.ts, src/utils/text-mappers.tsx
https://trello.com/c/jW25N0e5/2018-utvide-filteret-i-deltakerlisten
=> Legg til filter Hendelser for mine deltakertabell og koordinators tabell

src/component/felles/alert-info-message/AlertInfoMessage.tsx
https://trello.com/c/o246PosR/2024-oppdater-infotekster-om-lansering-av-vta-og-digital-jobbs%C3%B8kerkurs
=> Oppdater infotekster for TA etter lansering

src/hooks/useFeatureToggle.ts
https://trello.com/c/ewm6PMZr/2026-etter-lansering-legge-til-de-to-nye-tiltakstypene-i-listen-over-tiltak-vi-alltid-er-master-for
=> komet er alltid master for vasv og digiopparb

src/component/felles/alert-info-message/AlertInfoMessage.tsx
https://trello.com/c/8MBvUnyf/2028-fjerne-alertstriper
=> skjuler innføring alertstripe

index.html
https://trello.com/c/BitxfKNM/2098-bruke-hotjar-fra-dekorat%C3%B8ren
=> Tar bort hotjar oppsett for å bruke den som kommer fra dekoratøren

src/api/data/deltaker.ts, src/component/page/bruker-detaljer/deltaker-detaljer/forslag/ForslagSendt.tsx, src/component/page/deltakerliste-detaljer/filter-meny/FilterMenyHendelser.tsx, src/component/page/deltakerliste-detaljer/store/KoordinatorFilterContextProvider.tsx, src/component/page/veileder/filter-meny/FilterMenyHendelser.tsx, src/component/page/veileder/store/VeilederFilterContextProvider.tsx, src/utils/text-mappers.tsx
https://trello.com/c/twseYn27/2130-nytt-filter-oppdateringer-fra-nav
=> Vis oppdateringer fra nav

src/component/page/bruker-detaljer/deltaker-detaljer/vurdering/SettOppfyllerIkkeKravenelModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/vurdering/SettVurderingModal.module.scss
=> Alertstripe med info om vurdering som deles med arrangor

src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/endringsmodal/Endringsmodal.tsx
https://trello.com/c/JhD87tfF/2193-tekstendring-i-forslag-modal
=> Endre tekst i forslag modaler

src/api/data/forslag.ts, src/api/forslag-api.ts, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/AvsluttDeltakelseModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/AvsluttKursDeltakelseModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/validering/aarsakValidering.ts, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/validering/useAvsluttKursDeltakelseValidering.ts, src/component/page/bruker-detaljer/deltaker-detaljer/forslag/ForslagEndringsdetaljer.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/historikk/HistorikkElement.tsx, src/mock/data/historikk.ts, src/mock/setupMocks.ts
https://trello.com/c/dmPgsl3w/2163-tiltaksarrang%C3%B8r-avslutte-deltakelse-modal-skal-man-angi-om-kurset-er-fullf%C3%B8rt-eller-ikke
=> Avslutt deltakelse

src/component/page/bruker-detaljer/DeltakerDetaljer.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/vurdering/SettOppfyllerIkkeKravenelModal.tsx, src/mock/data/brukere.ts, src/mock/data/index.ts
https://trello.com/c/Z1KifHS1/2262-%C3%A5pne-for-at-arrang%C3%B8r-kan-vurdere-deltakere-p%C3%A5-gruppe-fag-og-yrke
=> Åpne opp for å gi vurdering på deltakere for gruppe fag og yrke

src/api/data/deltaker.ts, src/api/data/historikk.ts, src/component/page/bruker-detaljer/deltaker-detaljer/historikk/HistorikkEndring.tsx, src/mock/data/historikk.ts, src/mock/setupMocks.ts
https://trello.com/c/dmPgsl3w/2163-tiltaksarrang%C3%B8r-avslutte-deltakelse-modal-skal-man-angi-om-kurset-er-fullf%C3%B8rt-eller-ikke
=> Utvid avslutt deltakelse i historikken

src/component/felles/alert-info-message/sokt-inn-vurderes/AlertInfoMessageSoktInnVurderes.tsx
https://trello.com/c/b1Hy14X4/2303-oppdatere-tekst-i-infomelding-1
=> ny infomelding

src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/AvsluttDeltakelseModal.tsx, src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/AvsluttKursDeltakelseModal.tsx, src/utils/deltaker-utils.ts
https://trello.com/c/UHKI4IK3/2302-n%C3%A5r-skal-sp%C3%B8rsm%C3%A5let-kulepunktet-om-personen-har-deltatt-vises
=> Vise ikke deltatt bare innenfor femten dager

src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/AvsluttDeltakelseModal.tsx
https://trello.com/c/VUHU3b3u/2323-fiks-avslutt-deltakelse-verdier-for-l%C3%B8pende
=> Send null for fullført ved avslutt deltakelse løpende oppstart

src/component/page/bruker-detaljer/deltaker-detaljer/endre-deltaker-modal/varighet.ts
https://trello.com/c/KLYfHNYA/2398-endre-maks-makstid-p%C3%A5-avklaring-arr-og-digitalt-oppf%C3%B8lgingstiltak
=> Forleng maks varighet for ARBRRHDAG AVKLARAG og DIGIOPPARB med en uke
